version: '3'
services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
      - "./rabbitmq:/etc/giethoornharbor/"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_CONFIG_FILE=/etc/giethoornharbor/rabbitmq.conf

  sqlservergh:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sqlservergh
    volumes:
      - sqlserverdata:/var/opt/mssql
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - SA_PASSWORD=8jkGh47hnDw89Haq8LN2

  logserver:
    image: datalust/seq:latest
    container_name: logserver
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y

  shipsmanagementapi:
    image: giethoornharbor/shipsmanagementapi:1.0
    build: ShipsManagementAPI
    depends_on:
      - rabbitmq
      - sqlservergh
      - mongo
    ports:
      - "5100"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
        
  harbormanagementapi:
    image: giethoornharbor/harbormanagementapi:1.0
    build: HarborManagementAPI
    depends_on:
      - rabbitmq
      - sqlservergh
      - mongo
    ports:
      - "5200"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  auditlogservice:
    image: giethoornharbor/auditlogservice:1.0
    build: AuditlogService
    container_name: auditlogservice
    depends_on:
      - rabbitmq
    environment:
      - DOTNET_ENVIRONMENT=Production
        
  harbormanagementeventhandler:
    image: giethoornharbor/harbormanagementeventhandler:1.0
    build: HarborManagementEventHandler
    container_name: harbormanagementeventhandler
    depends_on:
      - rabbitmq
      - sqlservergh
      - mongo
      - harbormanagementapi
    environment:
      - DOTNET_ENVIRONMENT=Production
        
  shipmanagementeventhandler:
    image: giethoornharbor/shipmanagementeventhandler:1.0
    build: ShipManagementEventHandler
    container_name: shipmanagementeventhandler
    depends_on:
      - rabbitmq
      - sqlservergh
      - mongo
      - shipsmanagementapi
    environment:
      - DOTNET_ENVIRONMENT=Production
  
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    

volumes:
  sqlserverdata:
    external: true
  rabbitmqdata:
    external: true
  mongo_data:
    external: true
